### ISSUE TITLE
I'm getting an error but I don't know what it is.

### ISSUE THREAD

**Issue by PicklesJars** [corbindavenport/memebot#17]
```
[ OK ] You have the latest version of Memebot (3.0)
[ OK ] Setting up connection with Reddit...
[ OK ] Getting posts from Reddit
Traceback (most recent call last):
  File "C:/Users/Bobby Flay/Desktop/Python/memebot-3.0/memebot-3.0/memebot.py", line 362, in <module>
    main()
  File "C:/Users/Bobby Flay/Desktop/Python/memebot-3.0/memebot-3.0/memebot.py", line 226, in main
    post_dict = tweet_creator(subreddit)
  File "C:/Users/Bobby Flay/Desktop/Python/memebot-3.0/memebot-3.0/memebot.py", line 153, in tweet_creator
    for submission in subreddit_info.hot(limit=POST_LIMIT):
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\models\listing\generator.py", line 52, in __next__
    self._next_batch()
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\models\listing\generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\praw\reddit.py", line 472, in request
    params=params)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 181, in request
    params=params, url=url)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 112, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 97, in _make_request
    params=params)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\rate_limit.py", line 32, in call
    kwargs['headers'] = set_header_callback()
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\sessions.py", line 141, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 256, in refresh
    device_id=self._device_id)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\Bobby Flay\AppData\Local\Programs\Python\Python36-32\lib\site-packages\prawcore\auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
```
Why am I getting this?

**Comment by PicklesJars** [comment]
Nevermind I'm stupid
